name: Sync to Hugging Face Space

on:
  push:
    branches:
      - main # Or whichever branch you want to trigger deployment from

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the code from the GitHub repository with full history
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for proper syncing

      # Step 2: Install Git LFS
      - name: Setup Git LFS
        run: |
          git lfs install
          
      # Step 3: Configure Git with Hugging Face credentials
      - name: Configure Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          
      # Step 4: Manual sync to Hugging Face Space using Git
      - name: Push to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN_WRITE }}
        run: |
          # Create a fresh repository
          mkdir -p hf_repo
          cd hf_repo
          git init
          
          # Copy all files from GitHub checkout (excluding .git directory)
          cp -r ../$(ls -A .. | grep -v "^\.git$\|^hf_repo$") ./
          
          # Configure the remote
          git remote add origin https://USER:$HF_TOKEN@huggingface.co/spaces/sikeaditya/LLM-Cloud-Demo
          
          # Add and commit files
          git add .
          git commit -m "Automated sync from GitHub Actions"
          
          # Force push to the HF Space
          git push -f origin master:main