name: Sync to Hugging Face Space

on:
  push:
    branches:
      - main # Or whichever branch you want to trigger deployment from

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the code from the GitHub repository
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for proper syncing

      # Step 2: Setup Git LFS
      - name: Setup Git LFS
        run: |
          git lfs install

      # Step 3: Configure Git
      - name: Configure Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          
      # Step 4: List files to confirm what's available
      - name: List files
        run: |
          ls -la
          
      # Step 5: Create and push to Hugging Face Space
      - name: Push to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN_WRITE }}
        run: |
          # Clean any existing hf_repo directory
          rm -rf hf_repo
          
          # Create a new directory for the HF repo
          mkdir -p hf_repo
          
          # Copy specific files to the HF repo
          cp -r README.md app.py requirements.txt .github hf_repo/
          
          # Initialize git in the new directory
          cd hf_repo
          git init
          git branch -m main
          
          # Show what was copied
          ls -la
          
          # Set up the remote
          git remote add origin https://USER:$HF_TOKEN@huggingface.co/spaces/sikeaditya/LLM-Cloud-Demo
          
          # Add all files
          git add .
          
          # Commit files
          git commit -m "Automated sync from GitHub Actions"
          
          # Force push to HF Space
          git push -f origin main