name: Sync to Hugging Face Space

on:
  push:
    branches:
      - main # Or whichever branch you want to trigger deployment from

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the code from the GitHub repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Configure Git with Hugging Face credentials
      - name: Configure Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          
      # Step 3: Manual push to Hugging Face Space using Git
      - name: Push to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN_WRITE }}
        run: |
          # Clone the Hugging Face Space repository
          git clone https://huggingface.co/spaces/sikeaditya/LLM-Cloud-Demo huggingface-repo
          
          # Remove everything except .git directory
          find huggingface-repo -mindepth 1 -maxdepth 1 -not -name ".git" -exec rm -rf {} \;
          
          # Copy all files from GitHub repo to HF repo directory
          cp -r $(ls -A | grep -v "huggingface-repo") huggingface-repo/
          
          # Go to HF repo directory
          cd huggingface-repo
          
          # Add all changes to git
          git add .
          
          # Commit changes
          git commit -m "Automated sync from GitHub Actions" || echo "No changes to commit"
          
          # Push to Hugging Face Space with token authentication
          git push https://USER:$HF_TOKEN@huggingface.co/spaces/sikeaditya/LLM-Cloud-Demo main