name: Sync to Hugging Face Space

on:
  push:
    branches:
      - main # Or whichever branch you want to trigger deployment from

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the code from the GitHub repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Sync files to the Hugging Face Space repository
      - name: Push to Hub Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN_WRITE }}
        uses: huggingface/huggingface-sync@main
        with:
          # The Hugging Face repository type (space, model, dataset)
          repo_type: space
          # The Hugging Face Space ID (username/space_name)
          repo_id: sikeaditya/LLM-Cloud-Demo
          # The source directory in your GitHub repo containing the files to sync
          source_dir: .
          # Commit message for the push to the HF Space repo
          commit_message: "Automated sync from GitHub Actions"